package com.legalpro.accountservice.entity;

import com.legalpro.accountservice.enums.PayWayTransactionStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * One PayWay payment attempt. Saved as PENDING before calling
 * PayWay POST /transactions, then updated with PayWay's response.
 */
@Entity
@Table(name = "payway_transactions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PayWayTransaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Builder.Default
    @Column(nullable = false, unique = true, updatable = false)
    private UUID uuid = UUID.randomUUID();

    // --- Saved before calling PayWay ---

    // The invoice this attempt pays
    @Column(name = "invoice_uuid", nullable = false)
    private UUID invoiceUuid;

    @Column(name = "user_uuid", nullable = false)
    private UUID userUuid;

    @Column(name = "user_type", nullable = false)
    private String userType; // INDIVIDUAL | FIRM

    @Column(name = "company_uuid")
    private UUID companyUuid;

    @Column(name = "plan_id", nullable = false)
    private Long planId;

    @Column(name = "plan_duration", nullable = false)
    private String planDuration; // monthly | yearly

    @Column(name = "customer_number", nullable = false)
    private String customerNumber;

    // BJ<yyMMdd>-<sequence>, generated by the DB on insert
    @Generated(event = EventType.INSERT)
    @Column(name = "order_number", insertable = false, updatable = false)
    private String orderNumber;

    // Sent as PayWay's Idempotency-Key so a retried call can't charge twice
    @Builder.Default
    @Column(name = "idempotency_key", nullable = false, unique = true, updatable = false)
    private UUID idempotencyKey = UUID.randomUUID();

    @Column(nullable = false)
    private BigDecimal amount;

    @Column(name = "gst_amount", nullable = false)
    private BigDecimal gstAmount;

    @Column(name = "total_amount", nullable = false)
    private BigDecimal totalAmount;

    @Builder.Default
    @Column(nullable = false)
    private String currency = "aud";

    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PayWayTransactionStatus status = PayWayTransactionStatus.PENDING;

    // --- Saved from PayWay's response ---

    @Column(name = "payway_transaction_id")
    private Long paywayTransactionId;

    @Column(name = "receipt_number")
    private String receiptNumber;

    @Column(name = "payway_status")
    private String paywayStatus;

    @Column(name = "response_code")
    private String responseCode;

    @Column(name = "response_text")
    private String responseText;

    @Column(name = "surcharge_amount")
    private BigDecimal surchargeAmount;

    @Column(name = "payment_amount")
    private BigDecimal paymentAmount;

    @Column(name = "card_scheme")
    private String cardScheme;

    @Column(name = "masked_card_number")
    private String maskedCardNumber;

    @Column(name = "transaction_date_time")
    private String transactionDateTime;

    @Column(name = "settlement_date")
    private LocalDate settlementDate;

    @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;

    @PrePersist
    protected void onCreate() {
        if (uuid == null) uuid = UUID.randomUUID();
        if (idempotencyKey == null) idempotencyKey = UUID.randomUUID();
        createdAt = LocalDateTime.now();
        updatedAt = createdAt;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
