package com.legalpro.accountservice.entity;

import com.legalpro.accountservice.enums.SubscriptionInvoiceStatus;
import com.legalpro.accountservice.enums.SubscriptionInvoiceType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * One billing period for a subscriber. Payments (payway_transactions) are
 * attempts against an invoice; the invoice is PAID once one is approved.
 */
@Entity
@Table(name = "subscription_invoices")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SubscriptionInvoice {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Builder.Default
    @Column(nullable = false, unique = true, updatable = false)
    private UUID uuid = UUID.randomUUID();

    // INV<yyMMdd>-<sequence>, generated by the DB on insert
    @Generated(event = EventType.INSERT)
    @Column(name = "invoice_number", insertable = false, updatable = false)
    private String invoiceNumber;

    @Column(name = "user_uuid", nullable = false)
    private UUID userUuid;

    @Column(name = "user_type", nullable = false)
    private String userType; // INDIVIDUAL | FIRM

    @Column(name = "company_uuid")
    private UUID companyUuid;

    @Column(name = "user_subscription_uuid")
    private UUID userSubscriptionUuid;

    @Enumerated(EnumType.STRING)
    @Column(name = "invoice_type", nullable = false)
    private SubscriptionInvoiceType invoiceType;

    @Column(name = "plan_id", nullable = false)
    private Long planId;

    @Column(name = "plan_duration", nullable = false)
    private String planDuration; // monthly | yearly

    @Column(name = "period_start", nullable = false)
    private LocalDate periodStart;

    // Next billing date (exclusive)
    @Column(name = "period_end", nullable = false)
    private LocalDate periodEnd;

    @Column(name = "due_date", nullable = false)
    private LocalDate dueDate;

    @Column(nullable = false)
    private BigDecimal amount;

    @Column(name = "gst_amount", nullable = false)
    private BigDecimal gstAmount;

    @Column(name = "total_amount", nullable = false)
    private BigDecimal totalAmount;

    @Builder.Default
    @Column(nullable = false)
    private String currency = "aud";

    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private SubscriptionInvoiceStatus status = SubscriptionInvoiceStatus.DUE;

    @Column(name = "paid_at")
    private LocalDateTime paidAt;

    // Renewal charges declined so far; the subscription goes inactive after 3
    @Builder.Default
    @Column(name = "failed_attempts", nullable = false)
    private int failedAttempts = 0;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;

    @PrePersist
    protected void onCreate() {
        if (uuid == null) uuid = UUID.randomUUID();
        createdAt = LocalDateTime.now();
        updatedAt = createdAt;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
