-- PayWay (Westpac) card payments.
--
-- subscription_invoices: one row per billing period (first payment or renewal).
-- DUE until a payment for it is approved (PAID); OVERDUE if a renewal charge fails.
--
-- payway_transactions: one row per payment attempt against an invoice. Inserted
-- as PENDING before calling PayWay, then updated with PayWay's response.
--
-- payway_api_logs: audit trail of every HTTP call made to PayWay (request and
-- response), with sensitive values masked before they are written.

-- Order numbers: BJ<yyMMdd>-<sequence>, e.g. BJ261003-00000042 (17 chars).
-- Generated by the DB so they are unique, never reused, contain no personal
-- data, and fit PayWay's 20-character limit for orderNumber.
CREATE SEQUENCE payway_order_number_seq;

CREATE FUNCTION next_payway_order_number() RETURNS VARCHAR(20) LANGUAGE sql AS $$
    SELECT 'BJ' || to_char(now() AT TIME ZONE 'Australia/Melbourne', 'YYMMDD') || '-'
           || lpad(n.seq::text, greatest(8, length(n.seq::text)), '0')
    FROM (SELECT nextval('payway_order_number_seq') AS seq) n
$$;

-- Invoice numbers: INV<yyMMdd>-<sequence>, e.g. INV261003-00000042 (18 chars).
CREATE SEQUENCE subscription_invoice_number_seq;

CREATE FUNCTION next_subscription_invoice_number() RETURNS VARCHAR(20) LANGUAGE sql AS $$
    SELECT 'INV' || to_char(now() AT TIME ZONE 'Australia/Melbourne', 'YYMMDD') || '-'
           || lpad(n.seq::text, greatest(8, length(n.seq::text)), '0')
    FROM (SELECT nextval('subscription_invoice_number_seq') AS seq) n
$$;

CREATE TABLE subscription_invoices (
    id BIGSERIAL PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    invoice_number VARCHAR(20) NOT NULL UNIQUE DEFAULT next_subscription_invoice_number(),

    user_uuid UUID NOT NULL,                       -- payer (lawyer or firm admin)
    user_type VARCHAR(20) NOT NULL,                -- INDIVIDUAL | FIRM
    company_uuid UUID,                             -- set when user_type = FIRM
    user_subscription_uuid UUID,                   -- set once the subscription exists
    invoice_type VARCHAR(20) NOT NULL,             -- INITIAL | RENEWAL
    plan_id BIGINT NOT NULL,
    plan_duration VARCHAR(20) NOT NULL,            -- monthly | yearly

    period_start DATE NOT NULL,                    -- first day covered
    period_end DATE NOT NULL,                      -- next billing date (exclusive)
    due_date DATE NOT NULL,

    amount NUMERIC(10, 2) NOT NULL,                -- excl. GST
    gst_amount NUMERIC(10, 2) NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'aud',

    status VARCHAR(20) NOT NULL DEFAULT 'DUE',     -- DUE | PAID | OVERDUE | VOID
    paid_at TIMESTAMP,
    failed_attempts INT NOT NULL DEFAULT 0,        -- renewal charges declined so far (max 3)

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT fk_subscription_invoices_user FOREIGN KEY (user_uuid) REFERENCES accounts (uuid),
    CONSTRAINT fk_subscription_invoices_subscription FOREIGN KEY (user_subscription_uuid) REFERENCES user_subscriptions (uuid),
    CONSTRAINT fk_subscription_invoices_plan FOREIGN KEY (plan_id) REFERENCES subscriptions (id)
);

CREATE INDEX idx_subscription_invoices_user_uuid ON subscription_invoices (user_uuid);
CREATE INDEX idx_subscription_invoices_subscription ON subscription_invoices (user_subscription_uuid);
CREATE INDEX idx_subscription_invoices_status ON subscription_invoices (status);
CREATE INDEX idx_subscription_invoices_period_start ON subscription_invoices (period_start);

CREATE TABLE payway_transactions (
    id BIGSERIAL PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    -- Saved before calling PayWay
    invoice_uuid UUID NOT NULL,                    -- the invoice this attempt pays
    user_uuid UUID NOT NULL,                       -- logged-in payer (lawyer or firm admin)
    user_type VARCHAR(20) NOT NULL,                -- INDIVIDUAL | FIRM
    company_uuid UUID,                             -- set when user_type = FIRM
    plan_id BIGINT NOT NULL,
    plan_duration VARCHAR(20) NOT NULL,            -- monthly | yearly
    customer_number VARCHAR(20) NOT NULL,          -- LAW-<accounts.id> | FIRM-<companies.id>
    order_number VARCHAR(20) NOT NULL UNIQUE DEFAULT next_payway_order_number(),
    idempotency_key UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(), -- PayWay Idempotency-Key header

    amount NUMERIC(10, 2) NOT NULL,                -- excl. GST
    gst_amount NUMERIC(10, 2) NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,          -- sent to PayWay as principalAmount
    currency VARCHAR(3) NOT NULL DEFAULT 'aud',

    status VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING | APPROVED | DECLINED | ERROR

    -- Saved from PayWay's response
    payway_transaction_id BIGINT,
    receipt_number VARCHAR(64),
    payway_status VARCHAR(30),                     -- as returned: approved | approved* | declined | pending
    response_code VARCHAR(10),
    response_text VARCHAR(255),
    surcharge_amount NUMERIC(10, 2),
    payment_amount NUMERIC(10, 2),                 -- total actually charged
    card_scheme VARCHAR(30),
    masked_card_number VARCHAR(30),                -- as returned by PayWay, e.g. 456471...004
    transaction_date_time VARCHAR(40),             -- as returned, e.g. "30 Sep 2026 11:55 AEST"
    settlement_date DATE,
    error_message TEXT,                            -- PayWay rejected the request / unreachable

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,

    CONSTRAINT fk_payway_transactions_invoice FOREIGN KEY (invoice_uuid) REFERENCES subscription_invoices (uuid),
    CONSTRAINT fk_payway_transactions_user FOREIGN KEY (user_uuid) REFERENCES accounts (uuid),
    CONSTRAINT fk_payway_transactions_plan FOREIGN KEY (plan_id) REFERENCES subscriptions (id)
);

CREATE INDEX idx_payway_transactions_invoice_uuid ON payway_transactions (invoice_uuid);
CREATE INDEX idx_payway_transactions_user_uuid ON payway_transactions (user_uuid);
CREATE INDEX idx_payway_transactions_status ON payway_transactions (status);
CREATE INDEX idx_payway_transactions_customer_number ON payway_transactions (customer_number);
CREATE INDEX idx_payway_transactions_created_at ON payway_transactions (created_at);

-- At most one in-flight payment per payer: a double-clicked Pay button gets a
-- 409 instead of charging the card twice.
CREATE UNIQUE INDEX uq_payway_transactions_one_pending
    ON payway_transactions (user_uuid)
    WHERE status = 'PENDING';

-- PayWay customer holding the subscriber's saved card (charged on renewal)
ALTER TABLE user_subscriptions
    ADD COLUMN payway_customer_number VARCHAR(20);

CREATE INDEX idx_user_subscriptions_renews_at ON user_subscriptions (renews_at);

-- Audit log of PayWay API calls. Append-only: rows are never updated or deleted.
-- Masking (done in code before insert):
--   never stored : Authorization header (secret key), cardNumber, cvn, bank account numbers
--   masked       : singleUseTokenId -> last 4 chars only, e.g. ****6e20
--   stored as is : card numbers PayWay already masks in responses (456471...004)
CREATE TABLE payway_api_logs (
    id BIGSERIAL PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    payway_transaction_uuid UUID,                  -- the payment this call belongs to, if any
    user_uuid UUID,                                -- payer, if known

    operation VARCHAR(50) NOT NULL,                -- CREATE_TRANSACTION | GET_TRANSACTION | SAVE_CUSTOMER | ...
    http_method VARCHAR(10) NOT NULL,
    endpoint VARCHAR(255) NOT NULL,                -- path only, e.g. /transactions
    attempt INT NOT NULL DEFAULT 1,                -- 2 when the call was retried

    request_headers JSONB,                         -- masked
    request_body JSONB,                            -- masked
    response_status INT,                           -- HTTP status; NULL if no response (timeout)
    response_body JSONB,                           -- masked
    error_message TEXT,                            -- timeout / connection error
    duration_ms INT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payway_api_logs_transaction FOREIGN KEY (payway_transaction_uuid) REFERENCES payway_transactions (uuid),
    CONSTRAINT fk_payway_api_logs_user FOREIGN KEY (user_uuid) REFERENCES accounts (uuid)
);

CREATE INDEX idx_payway_api_logs_transaction ON payway_api_logs (payway_transaction_uuid);
CREATE INDEX idx_payway_api_logs_user_uuid ON payway_api_logs (user_uuid);
CREATE INDEX idx_payway_api_logs_operation ON payway_api_logs (operation);
CREATE INDEX idx_payway_api_logs_created_at ON payway_api_logs (created_at);
